//
// The MIT License (MIT)
//
// Copyright (c) 2021 HereweTech Co.LTD
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: proto/list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitDBResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDBResp) Reset() {
	*x = InitDBResp{}
	mi := &file_proto_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDBResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDBResp) ProtoMessage() {}

func (x *InitDBResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDBResp.ProtoReflect.Descriptor instead.
func (*InitDBResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{0}
}

func (x *InitDBResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Raw           bool                   `protobuf:"varint,4,opt,name=raw,proto3" json:"raw,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDef) Reset() {
	*x = ListDef{}
	mi := &file_proto_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDef) ProtoMessage() {}

func (x *ListDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDef.ProtoReflect.Descriptor instead.
func (*ListDef) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{1}
}

func (x *ListDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListDef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListDef) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

func (x *ListDef) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ListDef               `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	mi := &file_proto_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{2}
}

func (x *AddReq) GetItem() *ListDef {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,127,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResp) Reset() {
	*x = AddResp{}
	mi := &file_proto_list_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResp) ProtoMessage() {}

func (x *AddResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResp.ProtoReflect.Descriptor instead.
func (*AddResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{3}
}

func (x *AddResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,127,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_proto_list_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{4}
}

func (x *GetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ListDef               `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_proto_list_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{5}
}

func (x *GetResp) GetItem() *ListDef {
	if x != nil {
		return x.Item
	}
	return nil
}

type SetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ListDef               `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	mi := &file_proto_list_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{6}
}

func (x *SetReq) GetItem() *ListDef {
	if x != nil {
		return x.Item
	}
	return nil
}

type SetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           bool                   `protobuf:"varint,1,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResp) Reset() {
	*x = SetResp{}
	mi := &file_proto_list_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResp) ProtoMessage() {}

func (x *SetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResp.ProtoReflect.Descriptor instead.
func (*SetResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{7}
}

func (x *SetResp) GetSet() bool {
	if x != nil {
		return x.Set
	}
	return false
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,127,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_proto_list_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_proto_list_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResp) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset        int64                  `protobuf:"varint,254,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,255,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_proto_list_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{10}
}

func (x *ListReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ListDef             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_proto_list_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{11}
}

func (x *ListResp) GetItems() []*ListDef {
	if x != nil {
		return x.Items
	}
	return nil
}

type AllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllReq) Reset() {
	*x = AllReq{}
	mi := &file_proto_list_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReq) ProtoMessage() {}

func (x *AllReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReq.ProtoReflect.Descriptor instead.
func (*AllReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{12}
}

func (x *AllReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AllResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ListDef             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllResp) Reset() {
	*x = AllResp{}
	mi := &file_proto_list_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResp) ProtoMessage() {}

func (x *AllResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResp.ProtoReflect.Descriptor instead.
func (*AllResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{13}
}

func (x *AllResp) GetItems() []*ListDef {
	if x != nil {
		return x.Items
	}
	return nil
}

type CountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountReq) Reset() {
	*x = CountReq{}
	mi := &file_proto_list_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountReq) ProtoMessage() {}

func (x *CountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountReq.ProtoReflect.Descriptor instead.
func (*CountReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{14}
}

func (x *CountReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResp) Reset() {
	*x = CountResp{}
	mi := &file_proto_list_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResp) ProtoMessage() {}

func (x *CountResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResp.ProtoReflect.Descriptor instead.
func (*CountResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{15}
}

func (x *CountResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PurgeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeReq) Reset() {
	*x = PurgeReq{}
	mi := &file_proto_list_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeReq) ProtoMessage() {}

func (x *PurgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeReq.ProtoReflect.Descriptor instead.
func (*PurgeReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{16}
}

func (x *PurgeReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PurgeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purged        bool                   `protobuf:"varint,128,opt,name=purged,proto3" json:"purged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeResp) Reset() {
	*x = PurgeResp{}
	mi := &file_proto_list_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeResp) ProtoMessage() {}

func (x *PurgeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeResp.ProtoReflect.Descriptor instead.
func (*PurgeResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{17}
}

func (x *PurgeResp) GetPurged() bool {
	if x != nil {
		return x.Purged
	}
	return false
}

var File_proto_list_proto protoreflect.FileDescriptor

var file_proto_list_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x24, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6b, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x66,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x35, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x65, 0x66, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x19, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x7f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x7f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69,
	0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x66,
	0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x35, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x2b, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x66, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x1b, 0x0a,
	0x07, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73, 0x65, 0x74, 0x22, 0x1b, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x7f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22,
	0x4b, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0xfe, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x15, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0xff,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x39, 0x0a, 0x08,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69,
	0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x66,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x1a, 0x0a, 0x06, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x66, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x1c, 0x0a,
	0x08, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x21, 0x0a, 0x09, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1c,
	0x0a, 0x08, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x09,
	0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x06, 0x70, 0x75, 0x72,
	0x67, 0x65, 0x64, 0x18, 0x80, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x75, 0x72, 0x67,
	0x65, 0x64, 0x32, 0x9c, 0x04, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x49,
	0x6e, 0x69, 0x74, 0x44, 0x42, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e,
	0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x03, 0x41, 0x64, 0x64,
	0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x03, 0x53, 0x65, 0x74,
	0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63,
	0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x39, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a,
	0x03, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x05, 0x50, 0x75, 0x72, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x75,
	0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63,
	0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_list_proto_rawDescOnce sync.Once
	file_proto_list_proto_rawDescData []byte
)

func file_proto_list_proto_rawDescGZIP() []byte {
	file_proto_list_proto_rawDescOnce.Do(func() {
		file_proto_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_list_proto_rawDesc), len(file_proto_list_proto_rawDesc)))
	})
	return file_proto_list_proto_rawDescData
}

var file_proto_list_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_list_proto_goTypes = []any{
	(*InitDBResp)(nil),    // 0: svc.sicky.list.InitDBResp
	(*ListDef)(nil),       // 1: svc.sicky.list.ListDef
	(*AddReq)(nil),        // 2: svc.sicky.list.AddReq
	(*AddResp)(nil),       // 3: svc.sicky.list.AddResp
	(*GetReq)(nil),        // 4: svc.sicky.list.GetReq
	(*GetResp)(nil),       // 5: svc.sicky.list.GetResp
	(*SetReq)(nil),        // 6: svc.sicky.list.SetReq
	(*SetResp)(nil),       // 7: svc.sicky.list.SetResp
	(*DeleteReq)(nil),     // 8: svc.sicky.list.DeleteReq
	(*DeleteResp)(nil),    // 9: svc.sicky.list.DeleteResp
	(*ListReq)(nil),       // 10: svc.sicky.list.ListReq
	(*ListResp)(nil),      // 11: svc.sicky.list.ListResp
	(*AllReq)(nil),        // 12: svc.sicky.list.AllReq
	(*AllResp)(nil),       // 13: svc.sicky.list.AllResp
	(*CountReq)(nil),      // 14: svc.sicky.list.CountReq
	(*CountResp)(nil),     // 15: svc.sicky.list.CountResp
	(*PurgeReq)(nil),      // 16: svc.sicky.list.PurgeReq
	(*PurgeResp)(nil),     // 17: svc.sicky.list.PurgeResp
	(*emptypb.Empty)(nil), // 18: google.protobuf.Empty
}
var file_proto_list_proto_depIdxs = []int32{
	1,  // 0: svc.sicky.list.AddReq.item:type_name -> svc.sicky.list.ListDef
	1,  // 1: svc.sicky.list.GetResp.item:type_name -> svc.sicky.list.ListDef
	1,  // 2: svc.sicky.list.SetReq.item:type_name -> svc.sicky.list.ListDef
	1,  // 3: svc.sicky.list.ListResp.items:type_name -> svc.sicky.list.ListDef
	1,  // 4: svc.sicky.list.AllResp.items:type_name -> svc.sicky.list.ListDef
	18, // 5: svc.sicky.list.List.InitDB:input_type -> google.protobuf.Empty
	2,  // 6: svc.sicky.list.List.Add:input_type -> svc.sicky.list.AddReq
	4,  // 7: svc.sicky.list.List.Get:input_type -> svc.sicky.list.GetReq
	6,  // 8: svc.sicky.list.List.Set:input_type -> svc.sicky.list.SetReq
	8,  // 9: svc.sicky.list.List.Delete:input_type -> svc.sicky.list.DeleteReq
	10, // 10: svc.sicky.list.List.List:input_type -> svc.sicky.list.ListReq
	12, // 11: svc.sicky.list.List.All:input_type -> svc.sicky.list.AllReq
	14, // 12: svc.sicky.list.List.Count:input_type -> svc.sicky.list.CountReq
	16, // 13: svc.sicky.list.List.Purge:input_type -> svc.sicky.list.PurgeReq
	0,  // 14: svc.sicky.list.List.InitDB:output_type -> svc.sicky.list.InitDBResp
	3,  // 15: svc.sicky.list.List.Add:output_type -> svc.sicky.list.AddResp
	5,  // 16: svc.sicky.list.List.Get:output_type -> svc.sicky.list.GetResp
	7,  // 17: svc.sicky.list.List.Set:output_type -> svc.sicky.list.SetResp
	9,  // 18: svc.sicky.list.List.Delete:output_type -> svc.sicky.list.DeleteResp
	11, // 19: svc.sicky.list.List.List:output_type -> svc.sicky.list.ListResp
	13, // 20: svc.sicky.list.List.All:output_type -> svc.sicky.list.AllResp
	15, // 21: svc.sicky.list.List.Count:output_type -> svc.sicky.list.CountResp
	17, // 22: svc.sicky.list.List.Purge:output_type -> svc.sicky.list.PurgeResp
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_list_proto_init() }
func file_proto_list_proto_init() {
	if File_proto_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_list_proto_rawDesc), len(file_proto_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_list_proto_goTypes,
		DependencyIndexes: file_proto_list_proto_depIdxs,
		MessageInfos:      file_proto_list_proto_msgTypes,
	}.Build()
	File_proto_list_proto = out.File
	file_proto_list_proto_goTypes = nil
	file_proto_list_proto_depIdxs = nil
}
