//
// The MIT License (MIT)
//
// Copyright (c) 2021 HereweTech Co.LTD
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: proto/list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitDBResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *InitDBResp) Reset() {
	*x = InitDBResp{}
	mi := &file_proto_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDBResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDBResp) ProtoMessage() {}

func (x *InitDBResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDBResp.ProtoReflect.Descriptor instead.
func (*InitDBResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{0}
}

func (x *InitDBResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsJson bool   `protobuf:"varint,128,opt,name=is_json,json=isJson,proto3" json:"is_json,omitempty"`
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	mi := &file_proto_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{1}
}

func (x *ListItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListItem) GetIsJson() bool {
	if x != nil {
		return x.IsJson
	}
	return false
}

type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsJson bool   `protobuf:"varint,128,opt,name=is_json,json=isJson,proto3" json:"is_json,omitempty"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	mi := &file_proto_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{2}
}

func (x *AddReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AddReq) GetIsJson() bool {
	if x != nil {
		return x.IsJson
	}
	return false
}

type AddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,127,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddResp) Reset() {
	*x = AddResp{}
	mi := &file_proto_list_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResp) ProtoMessage() {}

func (x *AddResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResp.ProtoReflect.Descriptor instead.
func (*AddResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{3}
}

func (x *AddResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id     string `protobuf:"bytes,127,opt,name=id,proto3" json:"id,omitempty"`
	Offset int64  `protobuf:"varint,254,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64  `protobuf:"varint,255,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_proto_list_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{4}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*AddReq `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total int64     `protobuf:"varint,127,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_proto_list_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{5}
}

func (x *GetResp) GetItems() []*AddReq {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,127,opt,name=id,proto3" json:"id,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsJson bool   `protobuf:"varint,128,opt,name=is_json,json=isJson,proto3" json:"is_json,omitempty"`
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	mi := &file_proto_list_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{6}
}

func (x *SetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetReq) GetIsJson() bool {
	if x != nil {
		return x.IsJson
	}
	return false
}

type SetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSet bool `protobuf:"varint,128,opt,name=is_set,json=isSet,proto3" json:"is_set,omitempty"`
}

func (x *SetResp) Reset() {
	*x = SetResp{}
	mi := &file_proto_list_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResp) ProtoMessage() {}

func (x *SetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResp.ProtoReflect.Descriptor instead.
func (*SetResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{7}
}

func (x *SetResp) GetIsSet() bool {
	if x != nil {
		return x.IsSet
	}
	return false
}

type AllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AllReq) Reset() {
	*x = AllReq{}
	mi := &file_proto_list_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReq) ProtoMessage() {}

func (x *AllReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReq.ProtoReflect.Descriptor instead.
func (*AllReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{8}
}

func (x *AllReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AllResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*AddReq `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total int64     `protobuf:"varint,127,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *AllResp) Reset() {
	*x = AllResp{}
	mi := &file_proto_list_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResp) ProtoMessage() {}

func (x *AllResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResp.ProtoReflect.Descriptor instead.
func (*AllResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{9}
}

func (x *AllResp) GetItems() []*AddReq {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AllResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CountReq) Reset() {
	*x = CountReq{}
	mi := &file_proto_list_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountReq) ProtoMessage() {}

func (x *CountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountReq.ProtoReflect.Descriptor instead.
func (*CountReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{10}
}

func (x *CountReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CountResp) Reset() {
	*x = CountResp{}
	mi := &file_proto_list_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResp) ProtoMessage() {}

func (x *CountResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResp.ProtoReflect.Descriptor instead.
func (*CountResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{11}
}

func (x *CountResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,127,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_proto_list_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDeleted bool `protobuf:"varint,128,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_proto_list_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteResp) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type PurgeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PurgeReq) Reset() {
	*x = PurgeReq{}
	mi := &file_proto_list_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeReq) ProtoMessage() {}

func (x *PurgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeReq.ProtoReflect.Descriptor instead.
func (*PurgeReq) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{14}
}

func (x *PurgeReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PurgeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPurged bool `protobuf:"varint,128,opt,name=is_purged,json=isPurged,proto3" json:"is_purged,omitempty"`
}

func (x *PurgeResp) Reset() {
	*x = PurgeResp{}
	mi := &file_proto_list_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeResp) ProtoMessage() {}

func (x *PurgeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeResp.ProtoReflect.Descriptor instead.
func (*PurgeResp) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{15}
}

func (x *PurgeResp) GetIsPurged() bool {
	if x != nil {
		return x.IsPurged
	}
	return false
}

var File_proto_list_proto protoreflect.FileDescriptor

var file_proto_list_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x24, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4c, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x5f,
	0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x80, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4a,
	0x73, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x80, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22,
	0x19, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x7f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x7f, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0xfe, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x15, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x7f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x48, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x7f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x80, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22,
	0x21, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73,
	0x5f, 0x73, 0x65, 0x74, 0x18, 0x80, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x53,
	0x65, 0x74, 0x22, 0x1a, 0x0a, 0x06, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x4d,
	0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x7f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x1c, 0x0a,
	0x08, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x21, 0x0a, 0x09, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x1b,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x7f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x0a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x5f,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x80, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x1c, 0x0a, 0x08, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x09, 0x50, 0x75, 0x72, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x72, 0x67, 0x65,
	0x64, 0x18, 0x80, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x72, 0x67,
	0x65, 0x64, 0x32, 0xe1, 0x03, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x49,
	0x6e, 0x69, 0x74, 0x44, 0x42, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e,
	0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x03, 0x41, 0x64, 0x64,
	0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x03, 0x53, 0x65, 0x74,
	0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73,
	0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x18, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x19, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x05, 0x50, 0x75, 0x72, 0x67,
	0x65, 0x12, 0x18, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x73, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_list_proto_rawDescOnce sync.Once
	file_proto_list_proto_rawDescData = file_proto_list_proto_rawDesc
)

func file_proto_list_proto_rawDescGZIP() []byte {
	file_proto_list_proto_rawDescOnce.Do(func() {
		file_proto_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_list_proto_rawDescData)
	})
	return file_proto_list_proto_rawDescData
}

var file_proto_list_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_list_proto_goTypes = []any{
	(*InitDBResp)(nil),    // 0: svc.sicky.list.InitDBResp
	(*ListItem)(nil),      // 1: svc.sicky.list.ListItem
	(*AddReq)(nil),        // 2: svc.sicky.list.AddReq
	(*AddResp)(nil),       // 3: svc.sicky.list.AddResp
	(*GetReq)(nil),        // 4: svc.sicky.list.GetReq
	(*GetResp)(nil),       // 5: svc.sicky.list.GetResp
	(*SetReq)(nil),        // 6: svc.sicky.list.SetReq
	(*SetResp)(nil),       // 7: svc.sicky.list.SetResp
	(*AllReq)(nil),        // 8: svc.sicky.list.AllReq
	(*AllResp)(nil),       // 9: svc.sicky.list.AllResp
	(*CountReq)(nil),      // 10: svc.sicky.list.CountReq
	(*CountResp)(nil),     // 11: svc.sicky.list.CountResp
	(*DeleteReq)(nil),     // 12: svc.sicky.list.DeleteReq
	(*DeleteResp)(nil),    // 13: svc.sicky.list.DeleteResp
	(*PurgeReq)(nil),      // 14: svc.sicky.list.PurgeReq
	(*PurgeResp)(nil),     // 15: svc.sicky.list.PurgeResp
	(*emptypb.Empty)(nil), // 16: google.protobuf.Empty
}
var file_proto_list_proto_depIdxs = []int32{
	2,  // 0: svc.sicky.list.GetResp.items:type_name -> svc.sicky.list.AddReq
	2,  // 1: svc.sicky.list.AllResp.items:type_name -> svc.sicky.list.AddReq
	16, // 2: svc.sicky.list.List.InitDB:input_type -> google.protobuf.Empty
	2,  // 3: svc.sicky.list.List.Add:input_type -> svc.sicky.list.AddReq
	4,  // 4: svc.sicky.list.List.Get:input_type -> svc.sicky.list.GetReq
	6,  // 5: svc.sicky.list.List.Set:input_type -> svc.sicky.list.SetReq
	8,  // 6: svc.sicky.list.List.All:input_type -> svc.sicky.list.AllReq
	10, // 7: svc.sicky.list.List.Count:input_type -> svc.sicky.list.CountReq
	12, // 8: svc.sicky.list.List.Delete:input_type -> svc.sicky.list.DeleteReq
	14, // 9: svc.sicky.list.List.Purge:input_type -> svc.sicky.list.PurgeReq
	0,  // 10: svc.sicky.list.List.InitDB:output_type -> svc.sicky.list.InitDBResp
	3,  // 11: svc.sicky.list.List.Add:output_type -> svc.sicky.list.AddResp
	5,  // 12: svc.sicky.list.List.Get:output_type -> svc.sicky.list.GetResp
	7,  // 13: svc.sicky.list.List.Set:output_type -> svc.sicky.list.SetResp
	9,  // 14: svc.sicky.list.List.All:output_type -> svc.sicky.list.AllResp
	11, // 15: svc.sicky.list.List.Count:output_type -> svc.sicky.list.CountResp
	13, // 16: svc.sicky.list.List.Delete:output_type -> svc.sicky.list.DeleteResp
	15, // 17: svc.sicky.list.List.Purge:output_type -> svc.sicky.list.PurgeResp
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_list_proto_init() }
func file_proto_list_proto_init() {
	if File_proto_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_list_proto_goTypes,
		DependencyIndexes: file_proto_list_proto_depIdxs,
		MessageInfos:      file_proto_list_proto_msgTypes,
	}.Build()
	File_proto_list_proto = out.File
	file_proto_list_proto_rawDesc = nil
	file_proto_list_proto_goTypes = nil
	file_proto_list_proto_depIdxs = nil
}
